name: Build and deploy

on:
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy Winc app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd CD2
            git clone git@github.com:RonaldPolderman/CD2.git
            echo 'Deployment to Digital Ocean completed'
            sudo systemctl restart nginx
